Website.create!([
  {url: "agilewarrior.wordpress.com"},
  {url: "pl.wikipedia.org"},
  {url: "www.kingston.ac.uk"},
  {url: "open.spotify.com"},
  {url: "www.tvn24.pl"},
  {url: "antyweb.pl"},
  {url: "www.dobreprogramy.pl"},
  {url: "www.w3schools.com"},
  {url: "www.gry-online.pl"},
  {url: "www.windowscentral.com"},
  {url: "pauldix.blogs.com"},
  {url: "forum.rubyonrails.pl"},
  {url: "wiz.pwr.edu.pl"},
  {url: "swiatseriali.interia.pl"},
  {url: "www.filmweb.pl"},
  {url: "www.imdb.com"},
  {url: "twitter.com"},
  {url: "tech.wp.pl"},
  {url: "www.bbc.co.uk"},
  {url: "muzyka.onet.pl"},
  {url: "pl.bab.la"},
  {url: "www.diki.pl"},
  {url: "runthetrap.com"},
  {url: "icelandmag.visir.is"},
  {url: "edition.cnn.com"},
  {url: "www.telegraph.co.uk"},
  {url: "www.thesun.co.uk"},
  {url: "www.pudelek.tv"},
  {url: "www.pcadvisor.co.uk"},
  {url: "www.oracle.com"},
  {url: "www.elated.com"},
  {url: "www.smashingmagazine.com"},
  {url: "www.cgm.pl"},
  {url: "myapple.pl"},
  {url: "stackoverflow.com"},
  {url: "www.macworld.co.uk"},
  {url: "investorplace.com"},
  {url: "www.hulldailymail.co.uk"}
])
Bookmark.create!([
  {title: "How to add a flash message to your rails page | The Agile Warrior", description: "Rails flashes are just name value pair hashes To add them to your rails app go app/views/layouts/application.html.erb This will produce substituting the key value pair into the div. That’s why you can go flash[:error] and get a different style applied. Then in your controller all you have to do is controller.rb The nice styling you…", url: "https://agilewarrior.wordpress.com/2014/04/26/how-to-add-a-flash-message-to-your-rails-page/", short_url: "http://bk.mk/fbca6c8", website_id: 2},
  {title: "Tutorial – Wikipedia, wolna encyklopedia", description: nil, url: "https://pl.wikipedia.org/wiki/Tutorial", short_url: "http://bk.mk/b08c985", website_id: 7},
  {title: "studying on Spotify", description: nil, url: "https://open.spotify.com/user/11155888135/playlist/7CNJekIhRH14nP1sf8OpD7", short_url: "http://bk.mk/d126c63", website_id: 10},
  {title: "Karambol na autostradzie A2 w wielkanocny poniedziałek - TVN24", description: "23 auta zderzyły się w poniedziałek po południu na autostradzie A2 na trasie Poznań - Świecko, między węzłem Buk a węzłem Nowy Tomyśl. Jedna osoba zginęła....", url: "http://www.tvn24.pl/karambol-na-autostradzie-a2-w-wielkanocny-poniedzialek,732630,s.html", short_url: "http://bk.mk/b6a7c22", website_id: 11},
  {title: "Nowa aplikacja mBanku jest dokładnie tym, czego potrzebowałem", description: "mBank wprowadza nową aplikację na Androida ze wsparciem dla Android Pay. Debiutuje też BLIK QuickConnect i mechanizm analizujący tempo wydatków.", url: "http://antyweb.pl/nowa-aplikacja-mbanku/", short_url: "http://bk.mk/c013e34", website_id: 12},
  {title: "\r\n\tWindows 10: obsÅ\u0082uga kart w kaÅ¼dym oknie. IdÄ duÅ¼e zmiany w powÅ\u0082oce - dobreprogramy\r\n", description: "W marcu zeszÅ\u0082ego roku Peter Skillman, odpowiedzialny za rozwÃ³j interfejsu Windowsa, potwierdziÅ\u0082, Å¼e Microsoft pracuje nad gruntownymi zmianami w jednym z…", url: "https://www.dobreprogramy.pl/Windows-10-obsluga-kart-w-kazdym-oknie.-Ida-duze-zmiany-w-powloce,News,80522.html", short_url: "http://bk.mk/3dbb02d", website_id: 13},
  {title: "W3.JS Home", description: nil, url: "https://www.w3schools.com/w3js/default.asp", short_url: "http://bk.mk/15853dd", website_id: 14},
  {title: "Wielkanocne motywy, komiks Cartoon Games, odc. 208 | GRYOnline.pl", description: nil, url: "http://www.gry-online.pl/komiks.asp?ID=103463", short_url: "http://bk.mk/6dd7a3f", website_id: 15},
  {title: "Windows 10 Mobile is NOT dead — but its future is far from guaranteed | Windows Central", description: "The future of Windows 10 Mobile is as uncertain as ever. Here's what some recent changes to the Windows Insider Fast Ring mean for you and other Windows phone users.", url: "http://www.windowscentral.com/windows-10-mobile-not-dead-unclear-future?utm_medium=slider&utm_campaign=navigation&utm_source=wp", short_url: "http://bk.mk/10af812", website_id: 16},
  {title: "Windows Presentation Foundation – Wikipedia, wolna encyklopedia", description: nil, url: "https://pl.wikipedia.org/wiki/Windows_Presentation_Foundation", short_url: "http://bk.mk/7c9e9ab", website_id: 7},
  {title: "", description: nil, url: "http://pauldix.blogs.com/pauldix/goruco/classifying_documents_using_ruby.pdf", short_url: "http://bk.mk/c8ce132", website_id: 17},
  {title: "[colour.me / Wrocław] Full Stack Ruby Developers ( junior/mid/senior) - Praca / Projekty / Ogłoszenia - Polskie forum Ruby on Rails", description: "Colour.me to innowacyjna platforma e-commerce oferująca usługi i produkty w zakresie druku online i nie tylko... Wyróżnia nas pomysłowość i kreatywność. Stawiamy wyłącznie na funkcjonalne i efektywne rozwiązania. Prócz d&hellip;", url: "https://forum.rubyonrails.pl/t/colour-me-wroclaw-full-stack-ruby-developers-junior-mid-senior/12949", short_url: "http://bk.mk/1657ec7", website_id: 18},
  {title: "Harmonogram czynności / Wydział Informatyki i Zarządzania", description: nil, url: "http://wiz.pwr.edu.pl/studenci/organizacja-toku-studiow/harmonogram-czynnosci", short_url: "http://bk.mk/4128593", website_id: 19},
  {title: "\"Crime story\": Oko za oko - swiatseriali.pl", description: nil, url: "http://swiatseriali.interia.pl/newsy/seriale/kultowe-seriale-667/news-crime-story-oko-za-oko,nId,2381793", short_url: "http://bk.mk/77654a2", website_id: 20},
  {title: "Leslie Nielsen (I) - Filmweb", description: "Leslie Nielsen - Kariera ekranowego weterana komedii Leslie Nielsena jest wyjątkowo nietypowa: aktor osiągnął sukces dopiero po sześćdziesiątce, po 30. latach występowania w filmach i telewizji, i to...", url: "http://www.filmweb.pl/person/Leslie.Nielsen", short_url: "http://bk.mk/f519881", website_id: 21},
  {title: "'Star Wars' Stars Share Favorite Carrie Fisher Memories", description: "The cast and crew of 'Star Wars: The Last Jedi' at Star Wars Celebration reflect on some of their favorite memories of the late Carrie Fisher.", url: "http://www.imdb.com/list/ls069081936/videoplayer/vi2763766041?ref_=hm_sw_vd_i_1", short_url: "http://bk.mk/0322542", website_id: 22},
  {title: "Study Abroad and exchange programmes for visiting students - Kingston University London", description: "Find out more about studying at Kingston if you are studying outside the UK and would like to spend a semester or year abroad here as part of your degree at your home institution.", url: "http://www.kingston.ac.uk/visitingstudents/", short_url: "http://bk.mk/20999c1", website_id: 9},
  {title: "Kingston University (@KingstonUni) on Twitter", description: "The latest Tweets from Kingston University (@KingstonUni). Official news and updates from Kingston University London #makeitKU. Kingston upon Thames, London", url: "https://twitter.com/KingstonUni", short_url: "http://bk.mk/bae3378", website_id: 23},
  {title: "Bakterie made in Poland - WP Tech", description: "Istnieją przesłanki świadczące o tym, że w II RP prowadzono badania nad bronią biologiczną. Działania toksyn nie wahano się sprawdzać na więźniach – głównie schwytanych szpiegach. Przed kilkoma laty historyk i publicysta Andrzej Krajewski odkrył, że broń biologiczna była w centrum zainteresowania przedwojennych polskich bakteriologów. Wyniki swojej kwerendy przedstawił w artykule ”Kanapka ze śmiercią”, opublikowanym na łamach magazynu ”Focus Historia”. Dokumenty, do których dotarliśmy, potwierdzają, że pracownicy Oddziału II Sztabu Generalnego (polskiego wywiadu) poświęcali dużo uwagi kwestii ”wojny bakteriologicznej”. Z materiałów tych wyłania się niezwykle intrygujący obraz nieznanych dotąd obszarów działalności sanacji. I nie tylko – pewne tropy wiodą również do grupy, która miała stosować bakterie do walki z niemieckim okupantem.", url: "http://tech.wp.pl/bakterie-made-in-poland-6111963723097729g", short_url: "http://bk.mk/ee38e49", website_id: 24},
  {title: "North Korea 'will test missiles weekly', senior official tells BBC - BBC NewsBBC News", description: "A senior official tells the BBC this may happen \"weekly\", as the US warns: \"Don't test Trump.\"", url: "http://www.bbc.co.uk/news/world-asia-39623882", short_url: "http://bk.mk/a713474", website_id: 25},
  {title: "\n        \n            11- letnia córka Natalii Kukulskiej nagrała piosenkę - Muzyka\n        \n    ", description: "11-letnia Ania, córka Natalii Kukulskiej, rozpoczęła ostatnio naukę śpiewu. W sieci można już obejrzeć i posłuchać pierwszy teledysk z udziałem dziewczynki.", url: "http://muzyka.onet.pl/11-letnia-corka-natalii-kukulskiej-nagrala-piosenke/9wxb5m", short_url: "http://bk.mk/6330288", website_id: 26},
  {title: "daughter - tłumaczenie na polski - słownik angielsko-polski bab.la", description: "Tłumaczenie słowa 'daughter' i wiele innych tłumaczeń na polski - darmowy słownik angielsko-polski.", url: "http://pl.bab.la/slownik/angielski-polski/daughter", short_url: "http://bk.mk/1cf499c", website_id: 27},
  {title: "busker - Tłumaczenie po polsku - Słownik angielsko-polski Diki", description: "busker - tłumaczenie na polski oraz definicja. Co znaczy i jak powiedzieć \"busker\" po polsku? - uliczny artysta, grajek", url: "https://www.diki.pl/slownik-angielskiego?q=busker", short_url: "http://bk.mk/3d770f3", website_id: 28},
  {title: "This Notorious B.I.G. x Star Wars Mashup Mixtape is Glorious", description: nil, url: "http://runthetrap.com/2015/12/08/two-dudes-mashed-up-star-wars-movie-scores-w-notorious-b-i-g-tracks-the-result-is-glorious/", short_url: "http://bk.mk/e708710", website_id: 29},
  {title: "Photos: Monday's magnificent aurora over Kleifarvatn lake | Icelandmag", description: "Yesterday we were hit by a moderate geomagnetic storm, causing a particularly spectacular Northern Lights in the northern hemisphere. The According to the Icelandic Meteorological Office the Aurora activity in Iceland was \"strong\", or 7 on the 1-9 scale. Thanks to clear skies over most of Iceland we were treated to a spectacular show throughout the night and early morning.", url: "http://icelandmag.visir.is/article/photos-mondays-magnificent-aurora-over-kleifarvatn-lake", short_url: "http://bk.mk/85be6f9", website_id: 30},
  {title: "President Trump today: Live updates - CNNPolitics.com", description: "North Korea, China, Tax Day — and the President's first Easter egg roll. This is our live coverage of Trump's 88th day in the White House.", url: "http://edition.cnn.com/2017/04/17/politics/trump-north-korea-easter-roll-latest?lf-content=191869343:lb-post-094f29868dbab9aa3f0df8ca9b5949ee@livefyre.com&hubRefSrc=permalink", short_url: "http://bk.mk/3349a7c", website_id: 31},
  {title: "The 101 most useful websites - Telegraph", description: "There are tens of millions of sites to visit. Not forgetting telegraph.co.uk, here are the only ones you actually need. Compiled by David Baker.", url: "http://www.telegraph.co.uk/technology/3356874/The-101-most-useful-websites.html", short_url: "http://bk.mk/ac3a3d7", website_id: 32},
  {title: "Prince's home was found littered with prescription pills under the singer's secret alias Peter Bravestrong when cops probed his death, unseen documents reveal", description: "Court documents suggest star was suffering with an addiction to powerful drugs such as fentanyl, which he overdosed from", url: "https://www.thesun.co.uk/news/3349406/prince-home-found-prescription-pills-alias-peter-bravestrong/", short_url: "http://bk.mk/07c944b", website_id: 33},
  {title: "Lis o śmierci ojca: \"Zabierałam dzieci na onkologię. Miałam im powiedzieć, że schudł 20 kilo, bo miał uciążliwy katar?\" - PUDELEK.TV", description: "PUDELEK.TV - Lis o śmierci ojca: \"Zabierałam dzieci na onkologię. Miałam im powiedzieć, że schudł 20 kilo, bo miał uciążliwy katar?\" -  Sześć lat temu po ciężkiej walce z nowotworem zmarł ojciec Hanny Lis, komunistyczny dziennikarz Waldemar Kedaj. Na raka zmarli także jej babcia i dziadek. Dlatego dziennikarka regularnie, dwa razy do", url: "http://www.pudelek.tv/video/Lis-o-smierci-ojca-Zabieralam-dzieci-na-onkologie-Mialam-im-powiedziec-ze-schudl-20-kilo-bo-mial-uciazliwy-katar-15664/", short_url: "http://bk.mk/ec0f9dd", website_id: 34},
  {title: "Best Windows Phones 2017: Top Windows Phone Reviews & Buying Advice - PC Advisor", description: "Your guide to the latest and best Windows phones of 2017. Check out our latest reviews and buyer's guide on the top Windows phones for this year.", url: "http://www.pcadvisor.co.uk/test-centre/mobile-phone/best-windows-phones-for-2017-3265785/", short_url: "http://bk.mk/5768159", website_id: 35},
  {title: "Introduction to JQuery", description: nil, url: "http://www.oracle.com/technetwork/java/intro-jquery-166845.html", short_url: "http://bk.mk/7a63be2", website_id: 36},
  {title: "jQuery Mobile 1.4: Cleaner, Faster and More Powerful", description: "Find out what's new and improved in the jQuery Mobile 1.4 mobile web framework. The article includes detailed descriptions and demos that explain each new feature.", url: "http://www.elated.com/articles/jquery-mobile-1-4-cleaner-faster-more-powerful/", short_url: "http://bk.mk/f6602a1", website_id: 37},
  {title: "Which Responsive Design Framework Is Best? Of Course, It Depends. – Smashing Magazine", description: "Which framework should we be using, and why? Also, should we be using the whole framework or just parts of it? Find out in this article.", url: "https://www.smashingmagazine.com/2017/03/which-responsive-design-framework-is-best/", short_url: "http://bk.mk/0257703", website_id: 38},
  {title: "\n        \n            Czad Festiwal 2017: Steve Aoki na koncercie w Polsce - Muzyka\n        \n    ", description: "Czad Festiwal poszerzył swój skład. Do gwiazd imprezy dołączył Steve Aoki, czyli jeden z najpopularniejszych DJ-ów świata. Czad Festiwal odbędzie się w dniach 23-27 sierpnia 2017 roku w Straszęcinie.", url: "http://muzyka.onet.pl/klubowa/czad-festiwal-2017-steve-aoki-na-koncercie-w-polsce/qq6plx", short_url: "http://bk.mk/0348376", website_id: 26},
  {title: "Steve Aoki headlinerem polskiego festiwalu", description: nil, url: "http://www.cgm.pl/aktualnosci,48979,steve_aoki_headlinerem_polskiego_festiwalu,news.html", short_url: "http://bk.mk/9bd1bc8", website_id: 39},
  {title: "Apple udostÄ\u0099pniÅ\u0082o deweloperom najnowsze bety iOS, macOS, tvOS oraz watchOS - MyApple.pl", description: nil, url: "http://myapple.pl/posts/13717-apple-udostepnilo-deweloperom-najnowsze-bety-ios-macos-tvos-oraz-watchos", short_url: "http://bk.mk/7143be9", website_id: 40},
  {title: "struts2 - Difference between Token Interceptor and Token Session Interceptor? - Stack Overflow", description: nil, url: "http://stackoverflow.com/questions/19525888/difference-between-token-interceptor-and-token-session-interceptor", short_url: "http://bk.mk/1b417c2", website_id: 41},
  {title: "The 10 types of Apple fan: which one are you? - Macworld UK", description: "We outline the 10 types of Apple fan appearing live in the world around you today. Want to know what kind of Apple fan you are? Read on.", url: "http://www.macworld.co.uk/feature/apple/10-types-of-apple-fan-which-one-are-you-3594309/", short_url: "http://bk.mk/8f339b8", website_id: 42},
  {title: "McDonald's New Menu Items 2017: MCD Slushies Debut at 6,000 Locations | InvestorPlace", description: "McDonald's (MCD) is adding slushies to its menu at select locations in the Midwest and Southern parts of the United States.", url: "http://investorplace.com/2017/04/slushies-mcdonalds-new-menu-items-mcd/", short_url: "http://bk.mk/0fc966a", website_id: 43},
  {title: "\n\t\t\r\n            Bransholme set for huge new family pub and ten shops in 'super-estate' plans | Hull Daily Mail", description: " \n\tA \"super-estate\" planned for land near Bransholme is set to have its own family pub and a range of shops.\n \n \n\tDevelopers have revealed artist's impressions of how the new retail area on...", url: "http://www.hulldailymail.co.uk/bransholme-set-for-huge-new-family-pub-and-ten-shops-in-super-estate-plans/story-30271697-detail/story.html", short_url: "http://bk.mk/137e8d5", website_id: 44}
])
Tag.create!([
  {name: "stackoverflow"},
  {name: "non-model"},
  {name: "validation"},
  {name: "rails"},
  {name: "flash-message"},
  {name: "api"},
  {name: "new"},
  {name: "w3c"},
  {name: "web"},
  {name: "tutorial"},
  {name: "opinie"},
  {name: "marketing"},
  {name: "bmw"},
  {name: "smartfon"},
  {name: "wikipedia"},
  {name: "music"},
  {name: "interests"},
  {name: "hobby"},
  {name: "money"},
  {name: "sql"},
  {name: "css"},
  {name: "appml"},
  {name: "school"},
  {name: "spotify"},
  {name: "tvn24"},
  {name: "fakty"},
  {name: "poniedziałek"},
  {name: "mbank"},
  {name: "nowa-aplikacja"},
  {name: "super"},
  {name: "windows"},
  {name: "10"},
  {name: "w3c.js"},
  {name: "javascript"},
  {name: "komiks"},
  {name: "gry"},
  {name: "mobile"},
  {name: "future"},
  {name: "info"},
  {name: "classification"},
  {name: "ruby"},
  {name: "praca"},
  {name: "work"},
  {name: "wiz"},
  {name: "pwr"},
  {name: "uczelnia"},
  {name: "interia"},
  {name: "crime"},
  {name: "story"},
  {name: "actor"},
  {name: "movies"},
  {name: "films"},
  {name: "interview"},
  {name: "internationa"},
  {name: "students"},
  {name: "kingston"},
  {name: "uni"},
  {name: "twitter"},
  {name: "weapon"},
  {name: "poland"},
  {name: "bbc"},
  {name: "asia"},
  {name: "north-korea"},
  {name: "daughter"},
  {name: "song"},
  {name: "sings"},
  {name: "dictonary"},
  {name: "star"},
  {name: "wars"},
  {name: "notorious"},
  {name: "iceland"},
  {name: "visit"},
  {name: "travel"},
  {name: "trump"},
  {name: "useful"},
  {name: "websites"},
  {name: "telegraph"},
  {name: "prince"},
  {name: "drugs"},
  {name: "gossips"},
  {name: "lis"},
  {name: "phone"},
  {name: ""},
  {name: "best"},
  {name: "jquery"},
  {name: "article"},
  {name: "introuduction"},
  {name: "responsive"},
  {name: "framework"},
  {name: "steve"},
  {name: "aoki"},
  {name: "joins"},
  {name: "contert"},
  {name: "in"},
  {name: "apple"},
  {name: "ios"},
  {name: "everything"},
  {name: "tokens"},
  {name: "fan"},
  {name: "mcdonald's"},
  {name: "menu"},
  {name: "shops"}
])

BookmarkTag.create!([
  {bookmark_id: 2, tag_id: 4},
  {bookmark_id: 2, tag_id: 5},
  {bookmark_id: 7, tag_id: 15},
  {bookmark_id: 7, tag_id: 10},
  {bookmark_id: 17, tag_id: 16},
  {bookmark_id: 17, tag_id: 24},
  {bookmark_id: 18, tag_id: 25},
  {bookmark_id: 18, tag_id: 26},
  {bookmark_id: 18, tag_id: 27},
  {bookmark_id: 19, tag_id: 28},
  {bookmark_id: 19, tag_id: 29},
  {bookmark_id: 19, tag_id: 30},
  {bookmark_id: 20, tag_id: 31},
  {bookmark_id: 20, tag_id: 32},
  {bookmark_id: 21, tag_id: 33},
  {bookmark_id: 21, tag_id: 10},
  {bookmark_id: 21, tag_id: 34},
  {bookmark_id: 22, tag_id: 30},
  {bookmark_id: 22, tag_id: 35},
  {bookmark_id: 22, tag_id: 36},
  {bookmark_id: 23, tag_id: 31},
  {bookmark_id: 23, tag_id: 32},
  {bookmark_id: 23, tag_id: 37},
  {bookmark_id: 23, tag_id: 38},
  {bookmark_id: 24, tag_id: 15},
  {bookmark_id: 24, tag_id: 39},
  {bookmark_id: 24, tag_id: 31},
  {bookmark_id: 25, tag_id: 40},
  {bookmark_id: 25, tag_id: 41},
  {bookmark_id: 26, tag_id: 41},
  {bookmark_id: 26, tag_id: 42},
  {bookmark_id: 26, tag_id: 43},
  {bookmark_id: 27, tag_id: 44},
  {bookmark_id: 27, tag_id: 45},
  {bookmark_id: 27, tag_id: 46},
  {bookmark_id: 28, tag_id: 47},
  {bookmark_id: 28, tag_id: 48},
  {bookmark_id: 28, tag_id: 49},
  {bookmark_id: 29, tag_id: 50},
  {bookmark_id: 29, tag_id: 51},
  {bookmark_id: 29, tag_id: 52},
  {bookmark_id: 30, tag_id: 53},
  {bookmark_id: 31, tag_id: 54},
  {bookmark_id: 31, tag_id: 55},
  {bookmark_id: 31, tag_id: 56},
  {bookmark_id: 32, tag_id: 57},
  {bookmark_id: 32, tag_id: 46},
  {bookmark_id: 32, tag_id: 58},
  {bookmark_id: 33, tag_id: 59},
  {bookmark_id: 33, tag_id: 60},
  {bookmark_id: 34, tag_id: 61},
  {bookmark_id: 34, tag_id: 62},
  {bookmark_id: 34, tag_id: 63},
  {bookmark_id: 35, tag_id: 64},
  {bookmark_id: 35, tag_id: 65},
  {bookmark_id: 35, tag_id: 66},
  {bookmark_id: 36, tag_id: 67},
  {bookmark_id: 37, tag_id: 67},
  {bookmark_id: 38, tag_id: 16},
  {bookmark_id: 38, tag_id: 68},
  {bookmark_id: 38, tag_id: 69},
  {bookmark_id: 38, tag_id: 70},
  {bookmark_id: 39, tag_id: 71},
  {bookmark_id: 39, tag_id: 72},
  {bookmark_id: 39, tag_id: 73},
  {bookmark_id: 40, tag_id: 63},
  {bookmark_id: 40, tag_id: 74},
  {bookmark_id: 41, tag_id: 75},
  {bookmark_id: 41, tag_id: 76},
  {bookmark_id: 41, tag_id: 77},
  {bookmark_id: 42, tag_id: 78},
  {bookmark_id: 42, tag_id: 79},
  {bookmark_id: 43, tag_id: 80},
  {bookmark_id: 43, tag_id: 81},
  {bookmark_id: 44, tag_id: 31},
  {bookmark_id: 44, tag_id: 32},
  {bookmark_id: 44, tag_id: 82},
  {bookmark_id: 44, tag_id: 83},
  {bookmark_id: 44, tag_id: 84},
  {bookmark_id: 45, tag_id: 85},
  {bookmark_id: 45, tag_id: 86},
  {bookmark_id: 45, tag_id: 87},
  {bookmark_id: 46, tag_id: 85},
  {bookmark_id: 46, tag_id: 37},
  {bookmark_id: 47, tag_id: 9},
  {bookmark_id: 47, tag_id: 88},
  {bookmark_id: 47, tag_id: 89},
  {bookmark_id: 48, tag_id: 90},
  {bookmark_id: 48, tag_id: 91},
  {bookmark_id: 48, tag_id: 92},
  {bookmark_id: 48, tag_id: 93},
  {bookmark_id: 48, tag_id: 94},
  {bookmark_id: 48, tag_id: 60},
  {bookmark_id: 49, tag_id: 90},
  {bookmark_id: 49, tag_id: 91},
  {bookmark_id: 50, tag_id: 95},
  {bookmark_id: 50, tag_id: 7},
  {bookmark_id: 50, tag_id: 96},
  {bookmark_id: 50, tag_id: 7},
  {bookmark_id: 50, tag_id: 97},
  {bookmark_id: 51, tag_id: 1},
  {bookmark_id: 51, tag_id: 98},
  {bookmark_id: 52, tag_id: 95},
  {bookmark_id: 52, tag_id: 99},
  {bookmark_id: 53, tag_id: 100},
  {bookmark_id: 53, tag_id: 7},
  {bookmark_id: 53, tag_id: 101},
  {bookmark_id: 54, tag_id: 7},
  {bookmark_id: 54, tag_id: 102}
])
